<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Provides application hosting facilities for blazor server applications.</Description>
		<PackageTags></PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="..\Hosting.Blazor.Extensions\ApiServiceSettings.cs" Link="ApiServiceSettings.cs" />
		<Compile Include="..\Hosting.Blazor.Extensions\ApiServicesSettings.cs" Link="ApiServicesSettings.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hosting.Blazor.Extensions\Hosting.Blazor.Extensions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="SimpleInjector" Version="5.4.6" />
		<PackageReference Include="SimpleInjector.Integration.AspNetCore" Version="5.5.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

</Project>