<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Provides application hosting facilities for blazor server applications.</Description>
		<PackageTags></PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hosting.Blazor\Hosting.Blazor.csproj" />
		<ProjectReference Include="..\Hosting\Hosting.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="SimpleInjector" Version="5.4.4" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

</Project>