<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>TA.Composition</RootNamespace>
		<AssemblyName>TA.Composition</AssemblyName>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\Composition\Composition.csproj" />
	</ItemGroup>

</Project>