<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>TA.Composition</RootNamespace>
		<AssemblyName>TA.Composition</AssemblyName>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="RhoMicro.RequiredPropertyValidation.Generator" Version="3.0.2">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\Composition\Composition.csproj" />
		<ProjectReference Include="..\TA.Presentation.Views.Blazor\TA.Presentation.Views.Blazor.csproj" />
	</ItemGroup>

</Project>