<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<Description>Contains aspects, decorators, proxies, interceptors etc.</Description>
		<PackageTags></PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
	  <PackageReference Include="RhoMicro.CodeAnalysis.UnionsGenerator" Version="15.1.7">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="RhoMicro.RequiredPropertyValidation.Generator" Version="3.0.2">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="RhoMicro.RequiredPropertyValidation.Library" Version="3.0.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>

</Project>