<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<!--<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>-->
		<RootNamespace>RhoMicro.ApplicationFramework.Presentation.Views.Blazor</RootNamespace>
		<AssemblyName>RhoMicro.ApplicationFramework.Presentation.Views.Blazor</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.7" />
	</ItemGroup>

	<PropertyGroup>
		<Description>Contains views and base view abstractions.</Description>
		<PackageTags></PackageTags>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="/" CopyToOutputDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="RhoMicro.CodeAnalysis.UnionsGenerator" Version="15.1.6">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RhoMicro.RequiredPropertyValidation.Generator" Version="3.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RhoMicro.RequiredPropertyValidation.Library" Version="3.0.2" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hosting.Blazor\Hosting.Blazor.csproj" />
		<ProjectReference Include="..\Presentation.Views.Blazor.RenderModeGenerator\Presentation.Views.Blazor.RenderModeGenerator.csproj" OutputItemType="analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\Common\Common.csproj" />
		<ProjectReference Include="..\Presentation.Models\Presentation.Models.csproj" />
	</ItemGroup>

</Project>