<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>RMD.Composition</RootNamespace>
		<AssemblyName>RMD.Composition</AssemblyName>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Composition\Composition.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="SimpleInjector" Version="5.4.5" />
	</ItemGroup>

</Project>