<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>RMD.Composition</RootNamespace>
		<AssemblyName>RMD.Composition</AssemblyName>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Composition\Composition.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="RhoMicro.RequiredPropertyValidation.Generator" Version="3.0.2">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="RhoMicro.RequiredPropertyValidation.Library" Version="3.0.2" />
	  <PackageReference Include="SimpleInjector" Version="5.4.6" />
	</ItemGroup>

</Project>