<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest.TestFramework" Version="3.5.2" />
		<PackageReference Include="RhoMicro.RequiredPropertyValidation.Generator" Version="3.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RhoMicro.RequiredPropertyValidation.Library" Version="3.0.2" />
		<PackageReference Include="SimpleInjector" Version="5.5.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\Common.csproj" />
	</ItemGroup>

</Project>
