<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<RootNamespace>RMD.Presentation.LocalGui</RootNamespace>
		<AssemblyName>RMD.Presentation.LocalGui</AssemblyName>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="Photino.Blazor" Version="3.1.9" />
		<PackageReference Include="RhoMicro.RequiredPropertyValidation.Generator" Version="3.0.2">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="RhoMicro.RequiredPropertyValidation.Library" Version="3.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Hosting.Blazor.LocalGui\Hosting.Blazor.LocalGui.csproj" />
		<ProjectReference Include="..\RMD.Presentation.Views.Blazor\RMD.Presentation.Views.Blazor.csproj" />
		<ProjectReference Include="..\RMD.Composition\RMD.Composition.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Update="favicon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
