<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>TA.Presentation.WebGui</RootNamespace>
		<AssemblyName>TA.Presentation.WebGui</AssemblyName>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Hosting.Blazor.WebServerGui\Hosting.Blazor.WebServerGui.csproj" />
		<ProjectReference Include="..\TA.Composition\TA.Composition.csproj" />
		<ProjectReference Include="..\TA.Presentation.Views.Blazor\TA.Presentation.Views.Blazor.csproj" />
		<ProjectReference Include="..\TA.Presentation.WebGui.Client\TA.Presentation.WebGui.Client.csproj" />
	</ItemGroup>

</Project>
